---
abstract: 'plugin for Data::Compare to handle Set::Object objects'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  Carp: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Scalar::Util: '0'
  Set::Object: '0'
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Compare-Plugins-Set-Object
provides:
  Data::Compare::Plugins::Set::Object:
    file: lib/Data/Compare/Plugins/Set/Object.pm
    version: '1.002'
requires:
  Data::Compare: '0.06'
  English: '0'
  List::Util: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/mjgardner/Data-Compare-Plugins-Set-Object/issues
  homepage: http://search.cpan.org/dist/Data-Compare-Plugins-Set-Object/
  repository: git://github.com/mjgardner/Data-Compare-Plugins-Set-Object.git
version: '1.002'
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
